version: '3'
services:
    base:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: base
        #image: docker.pkg.github.com/thaibault/containerbase/base:latest
        image: tsickert/base:latest
        restart: always
