apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: '2019-10-12T18:55:07Z'
  labels:
    app: base
  name: base_pod
spec:
  containers:
  - env:
    - name: container
      value: podman
    image: ghcr.io/thaibault/containerbase:latest-x86-64
    name: base
