name: Test encrypted build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  encrypt:
    runs-on: ubuntu-latest
    container: ghcr.io/thaibault/containerbase:latest
    # NOTE: Theses environment variables are only needed to test the encrypt
    # script.
    env:
      DECRYPTED_PATHS: ./test/plain/
      ENCRYPTED_PATHS: ./test/encrypted/
      PASSWORD_FILE_PATHS: ./test/.encryptionPassword
    steps:
      - uses: actions/checkout@v2

      - run: ./encrypt.sh

      - run: rm --force --recursive test/encrypted
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # NOTE: If not set branch name will be used.
          tags: test

      - name: Build and push image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./test
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/thaibault/containerbase:test
    steps:
      - run: echo TODO Test run.
