name: Test encrypted build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  encrypt:
    runs-on: ubuntu-latest
    container: ghcr.io/thaibault/containerbase:latest
    # NOTE: Theses environment variables are only needed to test the encrypt
    # script.
    env:
      DECRYPTED_PATHS: test/plain/
      ENCRYPTED_PATHS: testAdvanced/testEncryption/
      PASSWORD_FILE_PATHS: testAdvanced/.encryptionPassword
    steps:
      - uses: actions/checkout@v2

      - run: ./encrypt.sh

      - run: rm --force --recursive testAdvanced/testEncryption
  buildAndRunSimple:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./testSimple
          push: false
          tags: testSimple:latest

      - uses: addnab/docker-run-action@v3
        with:
          image: testAdvanced:latest
  buildAndRunAdvanced:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./testAdvanced
          push: false
          tags: testAdvanced:latest

      - uses: addnab/docker-run-action@v3
        with:
          image: testAdvanced:latest
